# ==============================================================================
# Commercial-Grade AI Penetration Testing & Vulnerability Audit Platform
# Module: AI Logic Hunter — Request / Response Schema Definitions
# ==============================================================================

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, field_validator


class HunterAnalyzeRequest(BaseModel):
    """
    Input contract for the AI Logic Hunter analysis endpoint.
    Accepts raw HTTP traffic and an optional comparison-group credential
    for cross-account privilege-escalation (IDOR/BOLA) assessment.
    """
    raw_traffic: str = Field(
        ...,
        min_length=10,
        description=(
            "The raw HTTP request text pasted by the operator. "
            "Must include at least the request line and one header."
        ),
        examples=[
            "POST /api/v1/user/profile HTTP/1.1\n"
            "Host: target.example.com\n"
            "Cookie: session=abc123\n"
            "Content-Type: application/json\n\n"
            '{"user_id": 1001, "role": "admin"}'
        ],
    )

    auth_context_b: Optional[str] = Field(
        default=None,
        description=(
            "Comparison-group identity credential (e.g. another test account's Cookie, "
            "JWT, or UUID) used to help the AI evaluate horizontal/vertical privilege "
            "escalation (IDOR / BOLA) feasibility. Leave empty if not applicable."
        ),
        examples=["session=xyz789; user_id=2002"],
    )

    @field_validator("raw_traffic")
    @classmethod
    def validate_raw_traffic(cls, v: str) -> str:
        """Ensure the raw traffic is not just whitespace."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("raw_traffic must contain meaningful HTTP request content.")
        return stripped


class AutomationPayload(BaseModel):
    """
    A single attack-vector payload element produced by the AI reasoning engine.
    Designed for future automated fuzzing / replay execution.
    """
    phase: int = Field(
        ...,
        description="Execution phase: 1 = baseline probing, 2 = bypass & exploitation."
    )
    type: str = Field(
        ...,
        description="Vulnerability class (e.g. BOLA, IDOR, Parameter_Pollution, Race_Condition, Mass_Assignment)."
    )
    location: str = Field(
        ...,
        description="Where the target parameter resides: json_key, query_param, header, path_segment, cookie."
    )
    target_param: str = Field(
        ...,
        description="The exact parameter name to mutate (e.g. user_id, order_id, role)."
    )
    payload_string: str = Field(
        ...,
        description="The concrete payload action or replacement value to inject."
    )
    expected_match: str = Field(
        ...,
        description=(
            "The observable indicator to confirm exploitation success "
            "(e.g. HTTP 200, response length delta, specific error string)."
        ),
    )


class HunterAnalyzeResponse(BaseModel):
    """
    Output contract for the AI Logic Hunter analysis endpoint.
    Contains the structured parse result, AI-generated expert report,
    and machine-readable automation payloads.
    """
    status: str = Field(
        ...,
        description="Overall result status: 'success' or 'error'."
    )
    parsed_data: Dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "The structured HTTP request decomposition produced by the traffic parser. "
            "Contains: method, path, query_params, headers, body, errors."
        ),
    )
    report_markdown: str = Field(
        default="",
        description="Expert-level Markdown security analysis report generated by Gemini AI."
    )
    automation_payloads: List[AutomationPayload] = Field(
        default_factory=list,
        description="Array of structured attack-vector payloads for future automated replay."
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Human-readable error description when status is 'error'."
    )


# ==============================================================================
# Fuzzing Verification Schemas
# ==============================================================================

class FuzzingRecordSchema(BaseModel):
    """
    Output schema for a single FuzzingRecord entry — captures the mutated
    request, raw response, differential analysis verdict, and metrics.
    """
    id: str
    finding_id: int
    payload_index: int
    sent_request: Optional[str] = None
    received_response: Optional[str] = None
    verification_status: str
    diff_details: Optional[Dict[str, Any]] = None
    created_at: str

    class Config:
        from_attributes = True


class VerifyTriggerResponse(BaseModel):
    """
    Acknowledgement response when a fuzzing verification job is triggered.
    """
    status: str = Field(
        ...,
        description="'accepted' if the job was queued successfully."
    )
    finding_id: int = Field(
        ...,
        description="The finding ID that verification was triggered for."
    )
    message: str = Field(
        ...,
        description="Human-readable confirmation message."
    )


# ==============================================================================
# Step 8: Parallel Batch Verification & Identity Provider Dry-Run Schemas
# ==============================================================================

class AuthRefreshRequestSchema(BaseModel):
    """
    A transient (never-persisted) re-authentication request descriptor — the
    'Identity Provider Anchor'. Replayed by the custody state machine when the
    active session dies mid-scan.
    """
    method: str = Field(default="POST", description="HTTP method of the login/refresh request.")
    url: str = Field(..., description="Absolute URL of the identity/login endpoint.")
    headers: Dict[str, str] = Field(default_factory=dict, description="Request headers.")
    body: Optional[Any] = Field(default=None, description="Request body (JSON dict or raw string).")


class BatchVerifyRequest(BaseModel):
    """
    Input contract for parallel multi-endpoint fuzzing (Step 8 Objective B).
    All findings must resolve to a single approved host (v1 single-host lock).
    """
    finding_ids: List[int] = Field(..., min_length=1, description="Findings to fuzz concurrently.")
    scope: List[str] = Field(
        default_factory=list,
        description=(
            "Unified host-scope declaration: an allow-list of host patterns "
            "(e.g. ['example.com', '*.api.example.com', '10.0.0.5:8443']). Empty => UNLOCKED "
            "(lab/localhost, byte-identical to today). When set it supersedes approved_host and "
            "is the single authorized boundary all traffic is fail-closed to."
        ),
    )
    model: Optional[str] = Field(
        default=None,
        description=(
            "Optional per-run LLM model override for the shadow deep verifier "
            "(unset => the configured provider default)."
        ),
    )
    approved_host: Optional[str] = Field(
        default=None,
        description=(
            "LEGACY single approved host (netloc). Kept as a backward-compatible alias: when "
            "`scope` is empty this maps to scope=[approved_host]. Derived from findings if omitted."
        ),
    )
    auth_refresh_request: Optional[AuthRefreshRequestSchema] = Field(
        default=None,
        description="Transient re-auth request for the shared custody controller. Not persisted.",
    )
    max_concurrency: int = Field(
        default=5, ge=1, le=20,
        description="Global cap on concurrent outbound fuzz requests across the batch.",
    )


class BatchVerifyResponse(BaseModel):
    """Acknowledgement for a queued parallel verification batch."""
    status: str = Field(..., description="'accepted' if the batch was queued successfully.")
    finding_ids: List[int] = Field(..., description="The findings queued for verification.")
    approved_host: str = Field(..., description="The single host the batch is locked to.")
    message: str = Field(..., description="Human-readable confirmation message.")


class AuthDryRunRequest(BaseModel):
    """Request to test an Identity Provider Anchor before launching a batch."""
    auth_refresh_request: AuthRefreshRequestSchema
    approved_host: Optional[str] = Field(
        default=None,
        description="Optional scope lock; if set, the dry-run refuses out-of-scope hosts.",
    )


class AuthDryRunResponse(BaseModel):
    """Result of a re-auth dry-run probe."""
    success: bool = Field(..., description="True if a fresh credential was extracted.")
    status_code: Optional[int] = Field(default=None, description="HTTP status of the probe.")
    extracted_kind: Optional[str] = Field(default=None, description="'cookie' or 'token' if extracted.")
    extracted_preview: Optional[str] = Field(default=None, description="Truncated preview of the credential.")
    message: str = Field(..., description="Human-readable diagnostic.")


# ==============================================================================
# HAR Ingestion Schemas
# ==============================================================================

class HarIngestRequest(BaseModel):
    """
    Input contract for the HAR traffic ingestion endpoint.
    Accepts a standard HAR 1.2 JSON payload as produced by browser DevTools,
    Fiddler, Charles, mitmproxy, or Burp Suite exports.
    """
    log: Dict[str, Any] = Field(
        ...,
        description=(
            "The root 'log' object of a HAR 1.2 JSON file. "
            "Must contain an 'entries' array of HTTP request/response records."
        ),
    )

    threshold: float = Field(
        default=0.65,
        ge=0.0,
        le=1.0,
        description=(
            "Minimum exposure score threshold for traffic filtering. "
            "Entries below this score are pruned as noise. Default: 0.65."
        ),
    )


class HarIngestEntry(BaseModel):
    """
    A single high-value entry surfaced from HAR traffic pruning.
    """
    method: str = Field(..., description="HTTP method (GET, POST, etc.)")
    path: str = Field(..., description="Request URL path.")
    query_params: Dict[str, Any] = Field(default_factory=dict, description="Parsed query string parameters.")
    headers: Dict[str, str] = Field(default_factory=dict, description="Security-relevant request headers.")
    body: Optional[Any] = Field(default=None, description="Parsed request body (JSON dict or raw text).")
    exposure_score: float = Field(..., description="Computed heuristic exposure score [0.0, 1.0].")
    raw_http_string: str = Field(default="", description="Pre-reconstructed raw HTTP request text for direct textarea injection.")
    source_url: str = Field(default="", description="Original full URL from HAR entry.")
    is_login_candidate: bool = Field(
        default=False,
        description=(
            "Step 8: deterministically flagged as a likely identity/login endpoint "
            "(POST + login/auth/token/session/password markers). Used to pre-fill the "
            "Identity Provider Anchor panel for dynamic re-auth."
        ),
    )


class HarIngestResponse(BaseModel):
    """
    Output contract for the HAR ingestion endpoint.
    Returns filtered high-value endpoints after noise elimination.
    """
    status: str = Field(..., description="'success' or 'error'.")
    total_entries: int = Field(..., description="Total number of HAR entries received.")
    filtered_count: int = Field(..., description="Number of high-value entries after pruning.")
    threshold_used: float = Field(..., description="The exposure score threshold applied.")
    high_value_entries: List[HarIngestEntry] = Field(
        default_factory=list,
        description="Array of high-score entry points sorted by exposure score descending."
    )
    error_message: Optional[str] = Field(default=None, description="Error description if status is 'error'.")


# ==============================================================================
# Step D: Hunter Analysis Persistence Schemas
#
# Bridges the previously-broken Hunter -> Verify link: an analyzed request plus
# its AI-generated automation_payloads is persisted as a fuzzable
# VulnerabilityFinding (source="hunter"), returning a finding_id the verify
# endpoints can act on.
# ==============================================================================

class HunterPersistRequest(BaseModel):
    """
    Input contract for persisting an AI Logic Hunter analysis as a fuzzable
    finding. Structured data is stored in dedicated typed columns — NOT smuggled
    inside the ai_patch / poc_request text columns.
    """
    parsed_data: Dict[str, Any] = Field(
        ...,
        description=(
            "The structured HTTP request (method, path, query_params, headers, "
            "body) produced by /hunter/analyze. Stored in the parsed_request column."
        ),
    )
    automation_payloads: List[AutomationPayload] = Field(
        ...,
        min_length=1,
        description="The AI-generated attack payloads to fuzz. Stored in the automation_payloads column.",
    )
    target_url: Optional[str] = Field(
        default=None,
        description=(
            "Absolute base/target URL (scheme://host). Used to derive matched_at "
            "for the fuzzing base URL. If omitted, the backend derives it from the "
            "Host header inside parsed_data."
        ),
    )
    auth_refresh_request: Optional[AuthRefreshRequestSchema] = Field(
        default=None,
        description="Optional Identity Provider Anchor stored for single-target re-auth.",
    )
    report_markdown: Optional[str] = Field(
        default=None,
        description="Optional Gemini report markdown to retain in the ai_patch column for display.",
    )


class HunterPersistResponse(BaseModel):
    """Acknowledgement returned after persisting a Hunter analysis."""
    status: str = Field(..., description="'success' or 'error'.")
    finding_id: Optional[int] = Field(
        default=None,
        description="The integer id of the created VulnerabilityFinding (use with /verify/{finding_id}).",
    )
    message: str = Field(..., description="Human-readable confirmation or error diagnostic.")

